apiVersion: apps/v1
kind: Deployment
metadata:
  name: myappdb
  labels:
    app: myappdb
    type: database
spec:
  replicas: 3
  selector:
    matchLabels:
      type: database
  template:
    metadata:
      labels:
        app: myappdb
        type: database
    spec:
      containers:
      - name: database
        image: httpd:latest
        ports:
        - containerPort: 80

--- 

apiVersion: v1
kind: Service
metadata:
  name: database-service
spec:
  selector:
    type: database
  ports:
    - port: 80
      targetPort: 80
  type: NodePort